### ISSUE TITLE
Not able to integrate OOD-setup with HPC cluster

### ISSUE THREAD

**Issue by shankar0203** [aws-samples/open-on-demand-on-aws#22]
I am trying to integrate OOD-portal with HPC Cluster for that, i try to launch HPC-cluster by using OOD- stacks parameters. but the cloud formation template is failing with following error.
"WaitCondition received failed message: 'Failed to bootstrap the head node"
we are not able to get the cluster setup up/running.

**Comment by cpollard0** [comment]
Can you share your Parallel Cluster configuration file?

**Comment by dmorand17** [comment]
Closing stale issue.  @shankar0203 feel free to open a new issue if this is still a problem
