### ISSUE TITLE
Unable to enable RStudio

### ISSUE THREAD

**Issue by mwytang** [aws-samples/open-on-demand-on-aws#38]
Hello,

I am running issues with enabling the [RStudio App](https://github.com/OSC/bc_osc_rstudio_server).

Below is a description of how I launched Open OnDemand infrastructure in AWS:

- Launch the portal with the provided [CloudFormation template](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/cloudformation/openondemand.yml)
- Launch the HPC Cluster with the [sample script](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/scripts/create_sample_pcluster_config.sh). I provided the STACK_NAME, SSH_KEY, and REGION (us-east-1)
- Successfully enabled the provided Desktop app by creating /etc/ood/config/apps/bc_desktop/<cluster name>.yml

To enabled RStudio:

- I cloned the [repository ](https://github.com/OSC/bc_osc_rstudio_server) to /var/www/ood/apps/sys
- I created the file /etc/ood/config/apps/bc_osc_rstudio_server/<cluster name>.yml
```
title: "Sockeye RStudio"
cluster: <cluster name>
attributes:
  bc_num_slots: 1
form:
  - bc_queue
  - version
  - bc_num_hours
  - num_cores
  - num_types
```
- I updated [pcluster_worker_node_desktop.sh](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/scripts/pcluster_worker_node_desktop.sh): installed bubblewrap and uncomment the following lines
```
wget https://download2.rstudio.org/server/centos7/x86_64/rstudio-server-rhel-2023.03.0-386-x86_64.rpm
# run this on compute node
sudo yum install rstudio-server-rhel-2023.03.0-386-x86_64.rpm -y
systemctl start rstudio-server
```

The node initializes and runs, but will eventually time out and fail. Do you have suggestions of what the issue may be and how I can go about resolving it?

Thank you

**Comment by dmorand17** [comment]
Hi @mwytang I realize this issue is now quite stale but were you able to deploy RStudio?  I'd recommend you take a look at the Open OnDemand tutorial for adding [RStudio as an interactive app](https://osc.github.io/ood-documentation/latest/tutorials/tutorials-interactive-apps/add-rstudio.html).

**Comment by mwytang** [comment]
Hi @dmorand17, thank you for the follow up. I'll review the Open OnDemand tutorial to help troubleshoot the setup.
