### ISSUE TITLE
cannot access cluster via shell access

### ISSUE THREAD

**Issue by mwytang** [aws-samples/open-on-demand-on-aws#41]
I setup Open OnDemand with the [cloudformation template](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/cloudformation/openondemand.yml). I also used the [pcluster script](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/scripts/create_sample_pcluster_config.sh) to launch a ParallelCluster. 

The CloudFormation interface indicates they were all successful. I can also login to the Open OnDemand portal with the Admin account. However, when I try to connect to the cluster via Shell Access, I receive the following error.
 
![image](https://github.com/aws-samples/open-on-demand-on-aws/assets/1680669/9a3465cc-176e-46fe-b245-3fa594e5ec4b)
I noticed that some updates were made to the parallelcluster recently. Has anyone seen this issue before?

**Comment by QuintenSchrevens** [comment]
Facing the same issue...
if I find a fix i'll make sure to share it. 

I did find that in the [pcluster script](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/scripts/create_sample_pcluster_config.sh) the SSH key variable is not being used anywhere, not sure if this is actually influences the ssh communication between OOD and the Headnode.

**Comment by dmorand17** [comment]
[create_sample_pcluster_config.sh](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/scripts/create_sample_pcluster_config.sh) wasn't updated from the recent 3.1 upgrade.  I am working on a fix.

**Comment by dmorand17** [comment]
This has been addressed.  Pull down the latest `main` branch and re-create your ParallelCluster using the updated [scripts/create_sample_pcluster_config.sh](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/scripts/create_sample_pcluster_config.sh)

**Comment by QuintenSchrevens** [comment]
Thanks a lot for the fixes! 

the troubleshooting step you put in also helped me out a lot. 
needed to run it on both the OOD server and the Headnode to get it fixed
