### ISSUE TITLE
Pcluster questions

### ISSUE THREAD

**Issue by maestro7879** [aws-samples/open-on-demand-on-aws#43]
Is there a way to deploy AWS PC during the Cloudformation deployment ? 
If not is there a suggested way to deploy AWS PC ? Is it just using pcluster create-cluster from the OoD web portal manually ? 

Thanks!

**Comment by dmorand17** [comment]
You can use [create_sample_pcluster_config.sh](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/scripts/create_sample_pcluster_config.sh) to create a ParallelCluster configuration file that leverages the resources deployed from this OOD deployment.  Then use the normal `pcluster create-cluster` commands to create a cluster using the generated configuration.
