### ISSUE TITLE
Support for Pcluster 3.10.x

### ISSUE THREAD

**Issue by QuintenSchrevens** [aws-samples/open-on-demand-on-aws#44]
Hi, 

Would it be possible to add support for the latest Pcluster versions? 

Thanks!

**Comment by dmorand17** [comment]
Hi @QuintenSchrevens this solution should be compatible with the latest Pcluster version (3.10).  Is there a particular feature you are looking for?

**Comment by QuintenSchrevens** [comment]
When i try to deploy it with pcluster 3.10.1 it seems like the cluster does not register in OOD. 
when i access the headnode i get an error that the slum accounting with the db is not able to be opened (will add screenshot soon)

**Comment by dmorand17** [comment]
Thanks for that info @QuintenSchrevens I will make sure to test this out as part of some recent updates being made to the repo

**Comment by dmorand17** [comment]
I've verified that the installation is compatible with PC 3.10.1.  The most recent updates to this repo were tested against this version.
