### ISSUE TITLE
Can't launch stack

### ISSUE THREAD

**Issue by rsnorris** [aws-samples/open-on-demand-on-aws#48]
When I select the All-in-one Deployment, Launch Stack points me 404.

```
404 - page not found
The main branch of open-on-demand-on-aws does not contain the path "assets/cloudformation/ood-full.yml".
```

Here's the full URL
https://github.com/aws-samples/open-on-demand-on-aws/blob/main/"assets/cloudformation/ood-full.yml"

I think it's because it should be
https://github.com/aws-samples/open-on-demand-on-aws/blob/main/assets/cloudformation/ood_full.yml

**Comment by dmorand17** [comment]
Thanks @rsnorris I pushed up a fix for this issue
